const cellData = [
  { number: 1, type: 'start', icon: '🏁', color: '#e67e22', region: 'desert', connections: [2], description: 'Стартовая точка' },
  { number: 2, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [1, 3], description: 'Пустыня' },
  { number: 3, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [2, 4], description: 'Событие: найди сундук' },
  { number: 4, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [3, 5], description: 'Сундук с наградой' },
  { number: 5, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [4, 6], description: 'Пустыня' },
  { number: 6, type: 'npc', icon: '👾', color: '#e67e22', region: 'desert', connections: [5, 7], description: 'NPC: продавец' },
  { number: 7, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [6, 8], description: 'Пустыня' },
  { number: 8, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [7, 9], description: 'Событие: мини-игра' },
  { number: 9, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [8, 10], description: 'Пустыня' },
  { number: 10, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [9, 11], description: 'Босс: пустынный гигант' },
  { number: 11, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [10, 12], description: 'Лес' },
  { number: 12, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [11, 13], description: 'Событие: спаси дерево' },
  { number: 13, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [12, 14], description: 'Сундук с зельем' },
  { number: 14, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [13, 15], description: 'Лес' },
  { number: 15, type: 'npc', icon: '👾', color: '#2ecc71', region: 'forest', connections: [14, 16], description: 'NPC: охотник' },
  { number: 16, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [15, 17], description: 'Лес' },
  { number: 17, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [16, 18], description: 'Событие: убей монстра' },
  { number: 18, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [17, 19], description: 'Лес' },
  { number: 19, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [18, 20], description: 'Босс: лесной дух' },
  { number: 20, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [19, 21], description: 'Вода' },
  { number: 21, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [20, 22], description: 'Событие: плавание' },
  { number: 22, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [21, 23], description: 'Сундук на дне' },
  { number: 23, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [22, 24], description: 'Вода' },
  { number: 24, type: 'npc', icon: '🐙', color: '#3498db', region: 'water', connections: [23, 25], description: 'NPC: осьминог' },
  { number: 25, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [24, 26], description: 'Вода' },
  { number: 26, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [25, 27], description: 'Событие: буря' },
  { number: 27, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [26, 28], description: 'Вода' },
  { number: 28, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [27, 29], description: 'Босс: морской змей' },
  { number: 29, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [28, 30], description: 'Горы' },
  { number: 30, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [29, 31], description: 'Событие: восхождение' },
  { number: 31, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [30, 32], description: 'Сундук на вершине' },
  { number: 32, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [31, 33], description: 'Горы' },
  { number: 33, type: 'npc', icon: '🏔️', color: '#9b59b6', region: 'mountains', connections: [32, 34], description: 'NPC: альпинист' },
  { number: 34, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [33, 35], description: 'Горы' },
  { number: 35, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [34, 36], description: 'Событие: лавина' },
  { number: 36, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [35, 37], description: 'Горы' },
  { number: 37, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [36, 38], description: 'Босс: горный тролль' },
  { number: 38, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [37, 39], description: 'Снег' },
  { number: 39, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [38, 40], description: 'Событие: лыжная гонка' },
  { number: 40, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [39, 41], description: 'Сундук в сугробе' },
  { number: 41, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [40, 42], description: 'Снег' },
  { number: 42, type: 'npc', icon: '🐧', color: '#ecf0f1', region: 'snow', connections: [41, 43], description: 'NPC: пингвин' },
  { number: 43, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [42, 44], description: 'Снег' },
  { number: 44, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [43, 45], description: 'Событие: метель' },
  { number: 45, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [44, 46], description: 'Снег' },
  { number: 46, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [45, 47], description: 'Босс: снежный великан' },
  { number: 47, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [46, 48], description: 'Лава' },
  { number: 48, type: 'event', icon: '✅', color: '#e74c3c', region: 'lava', connections: [47, 49], description: 'Событие: прыжок через лаву' },
  { number: 49, type: 'chest', icon: '💰', color: '#e74c3c', region: 'lava', connections: [48, 50], description: 'Сундук в кратере' },
  { number: 50, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [49, 51], description: 'Лава' },
  { number: 51, type: 'npc', icon: '🔥', color: '#e74c3c', region: 'lava', connections: [50, 52], description: 'NPC: демон' },
  { number: 52, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [51, 53], description: 'Лава' },
  { number: 53, type: 'event', icon: '❌', color: '#e74c3c', region: 'lava', connections: [52, 54], description: 'Событие: извержение' },
  { number: 54, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [53, 55], description: 'Лава' },
  { number: 55, type: 'boss', icon: '🎯', color: '#e74c3c', region: 'lava', connections: [54, 56], description: 'Босс: повелитель огня' },
  { number: 56, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [55, 57], description: 'Пустыня' },
  { number: 57, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [56, 58], description: 'Событие: найди оазис' },
  { number: 58, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [57, 59], description: 'Сундук с водой' },
  { number: 59, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [58, 60], description: 'Пустыня' },
  { number: 60, type: 'npc', icon: '🐪', color: '#e67e22', region: 'desert', connections: [59, 61], description: 'NPC: верблюд' },
  { number: 61, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [60, 62], description: 'Пустыня' },
  { number: 62, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [61, 63], description: 'Событие: песчаная буря' },
  { number: 63, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [62, 64], description: 'Пустыня' },
  { number: 64, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [63, 65], description: 'Босс: песчаный червь' },
  { number: 65, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [64, 66], description: 'Лес' },
  { number: 66, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [65, 67], description: 'Событие: собери ягоды' },
  { number: 67, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [66, 68], description: 'Сундук с медом' },
  { number: 68, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [67, 69], description: 'Лес' },
  { number: 69, type: 'npc', icon: '🐻', color: '#2ecc71', region: 'forest', connections: [68, 70], description: 'NPC: медведь' },
  { number: 70, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [69, 71], description: 'Лес' },
  { number: 71, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [70, 72], description: 'Событие: пожар' },
  { number: 72, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [71, 73], description: 'Лес' },
  { number: 73, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [72, 74], description: 'Босс: король леса' },
  { number: 74, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [73, 75], description: 'Вода' },
  { number: 75, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [74, 76], description: 'Событие: рыбалка' },
  { number: 76, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [75, 77], description: 'Сундук с жемчугом' },
  { number: 77, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [76, 78], description: 'Вода' },
  { number: 78, type: 'npc', icon: '🐠', color: '#3498db', region: 'water', connections: [77, 79], description: 'NPC: рыбак' },
  { number: 79, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [78, 80], description: 'Вода' },
  { number: 80, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [79, 81], description: 'Событие: шторм' },
  { number: 81, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [80, 82], description: 'Вода' },
  { number: 82, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [81, 83], description: 'Босс: кракен' },
  { number: 83, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [82, 84], description: 'Горы' },
  { number: 84, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [83, 85], description: 'Событие: скалолазание' },
  { number: 85, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [84, 86], description: 'Сундук с кристаллом' },
  { number: 86, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [85, 87], description: 'Горы' },
  { number: 87, type: 'npc', icon: '⛰️', color: '#9b59b6', region: 'mountains', connections: [86, 88], description: 'NPC: скалолаз' },
  { number: 88, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [87, 89], description: 'Горы' },
  { number: 89, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [88, 90], description: 'Событие: камнепад' },
  { number: 90, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [89, 91], description: 'Горы' },
  { number: 91, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [90, 92], description: 'Босс: горный циклоп' },
  { number: 92, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [91, 93], description: 'Снег' },
  { number: 93, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [92, 94], description: 'Событие: снежный ком' },
  { number: 94, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [93, 95], description: 'Сундук с шубой' },
  { number: 95, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [94, 96], description: 'Снег' },
  { number: 96, type: 'npc', icon: '❄️', color: '#ecf0f1', region: 'snow', connections: [95, 97], description: 'NPC: снеговик' },
  { number: 97, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [96, 98], description: 'Снег' },
  { number: 98, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [97, 99], description: 'Событие: снежная буря' },
  { number: 99, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [98, 100], description: 'Снег' },
  { number: 100, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [99, 101], description: 'Босс: ледяной дракон' },
  { number: 101, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [100, 102], description: 'Пустыня' },
  { number: 102, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [101, 103], description: 'Событие: найди ключ' },
  { number: 103, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [102, 104], description: 'Сундук с ключом' },
  { number: 104, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [103, 105], description: 'Пустыня' },
  { number: 105, type: 'npc', icon: '🦂', color: '#e67e22', region: 'desert', connections: [104, 106], description: 'NPC: скорпион' },
  { number: 106, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [105, 107], description: 'Пустыня' },
  { number: 107, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [106, 108], description: 'Событие: яма' },
  { number: 108, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [107, 109], description: 'Пустыня' },
  { number: 109, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [108, 110], description: 'Босс: песчаный маг' },
  { number: 110, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [109, 111], description: 'Лес' },
  { number: 111, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [110, 112], description: 'Событие: найди яйцо' },
  { number: 112, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [111, 113], description: 'Сундук с яйцом' },
  { number: 113, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [112, 114], description: 'Лес' },
  { number: 114, type: 'npc', icon: '🦅', color: '#2ecc71', region: 'forest', connections: [113, 115], description: 'NPC: орёл' },
  { number: 115, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [114, 116], description: 'Лес' },
  { number: 116, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [115, 117], description: 'Событие: падение дерева' },
  { number: 117, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [116, 118], description: 'Лес' },
  { number: 118, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [117, 119], description: 'Босс: дракон-дятел' },
  { number: 119, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [118, 120], description: 'Вода' },
  { number: 120, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [119, 121], description: 'Событие: подводное плавание' },
  { number: 121, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [120, 122], description: 'Сундук с жемчужиной' },
  { number: 122, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [121, 123], description: 'Вода' },
  { number: 123, type: 'npc', icon: '🐬', color: '#3498db', region: 'water', connections: [122, 124], description: 'NPC: дельфин' },
  { number: 124, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [123, 125], description: 'Вода' },
  { number: 125, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [124, 126], description: 'Событие: акула' },
  { number: 126, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [125, 127], description: 'Вода' },
  { number: 127, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [126, 128], description: 'Босс: акулья стая' },
  { number: 128, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [127, 129], description: 'Горы' },
  { number: 129, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [128, 130], description: 'Событие: найди руду' },
  { number: 130, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [129, 131], description: 'Сундук с рудой' },
  { number: 131, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [130, 132], description: 'Горы' },
  { number: 132, type: 'npc', icon: '⛏️', color: '#9b59b6', region: 'mountains', connections: [131, 133], description: 'NPC: шахтёр' },
  { number: 133, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [132, 134], description: 'Горы' },
  { number: 134, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [133, 135], description: 'Событие: обвал' },
  { number: 135, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [134, 136], description: 'Горы' },
  { number: 136, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [135, 137], description: 'Босс: горный дракон' },
  { number: 137, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [136, 138], description: 'Снег' },
  { number: 138, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [137, 139], description: 'Событие: найди лед' },
  { number: 139, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [138, 140], description: 'Сундук с льдом' },
  { number: 140, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [139, 141], description: 'Снег' },
  { number: 141, type: 'npc', icon: '☃️', color: '#ecf0f1', region: 'snow', connections: [140, 142], description: 'NPC: снеговик' },
  { number: 142, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [141, 143], description: 'Снег' },
  { number: 143, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [142, 144], description: 'Событие: снежок' },
  { number: 144, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [143, 145], description: 'Снег' },
  { number: 145, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [144, 146], description: 'Босс: снежный монстр' },
  { number: 146, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [145, 147], description: 'Лава' },
  { number: 147, type: 'event', icon: '✅', color: '#e74c3c', region: 'lava', connections: [146, 148], description: 'Событие: найди кристалл огня' },
  { number: 148, type: 'chest', icon: '💰', color: '#e74c3c', region: 'lava', connections: [147, 149], description: 'Сундук с кристаллом' },
  { number: 149, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [148, 150], description: 'Лава' },
  { number: 150, type: 'npc', icon: '🌋', color: '#e74c3c', region: 'lava', connections: [149, 151], description: 'NPC: вулкан' },
  { number: 151, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [150, 152], description: 'Лава' },
  { number: 152, type: 'event', icon: '❌', color: '#e74c3c', region: 'lava', connections: [151, 153], description: 'Событие: лавовый поток' },
  { number: 153, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [152, 154], description: 'Лава' },
  { number: 154, type: 'boss', icon: '🎯', color: '#e74c3c', region: 'lava', connections: [153, 155], description: 'Босс: огненный дракон' },
  { number: 155, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [154, 156], description: 'Пустыня' },
  { number: 156, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [155, 157], description: 'Событие: найди золото' },
  { number: 157, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [156, 158], description: 'Сундук с золотом' },
  { number: 158, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [157, 159], description: 'Пустыня' },
  { number: 159, type: 'npc', icon: '🐫', color: '#e67e22', region: 'desert', connections: [158, 160], description: 'NPC: двугорбый верблюд' },
  { number: 160, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [159, 161], description: 'Пустыня' },
  { number: 161, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [160, 162], description: 'Событие: смерч' },
  { number: 162, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [161, 163], description: 'Пустыня' },
  { number: 163, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [162, 164], description: 'Босс: пустынный шейх' },
  { number: 164, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [163, 165], description: 'Лес' },
  { number: 165, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [164, 166], description: 'Событие: найди мёд' },
  { number: 166, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [165, 167], description: 'Сундук с мёдом' },
  { number: 167, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [166, 168], description: 'Лес' },
  { number: 168, type: 'npc', icon: '🐝', color: '#2ecc71', region: 'forest', connections: [167, 169], description: 'NPC: пчёлы' },
  { number: 169, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [168, 170], description: 'Лес' },
  { number: 170, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [169, 171], description: 'Событие: улей' },
  { number: 171, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [170, 172], description: 'Лес' },
  { number: 172, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [171, 173], description: 'Босс: королева пчёл' },
  { number: 173, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [172, 174], description: 'Вода' },
  { number: 174, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [173, 175], description: 'Событие: найди жемчужину' },
  { number: 175, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [174, 176], description: 'Сундук с жемчужиной' },
  { number: 176, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [175, 177], description: 'Вода' },
  { number: 177, type: 'npc', icon: '🐋', color: '#3498db', region: 'water', connections: [176, 178], description: 'NPC: кит' },
  { number: 178, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [177, 179], description: 'Вода' },
  { number: 179, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [178, 180], description: 'Событие: цунами' },
  { number: 180, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [179, 181], description: 'Вода' },
  { number: 181, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [180, 182], description: 'Босс: морской титан' },
  { number: 182, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [181, 183], description: 'Горы' },
  { number: 183, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [182, 184], description: 'Событие: найди алмаз' },
  { number: 184, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [183, 185], description: 'Сундук с алмазом' },
  { number: 185, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [184, 186], description: 'Горы' },
  { number: 186, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [185, 187], description: 'NPC: кристалл' },
  { number: 187, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [186, 188], description: 'Горы' },
  { number: 188, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [187, 189], description: 'Событие: оползень' },
  { number: 189, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [188, 190], description: 'Горы' },
  { number: 190, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [189, 191], description: 'Босс: алмазный гигант' },
  { number: 191, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [190, 192], description: 'Снег' },
  { number: 192, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [191, 193], description: 'Событие: найди снежинку' },
  { number: 193, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [192, 194], description: 'Сундук со снежинкой' },
  { number: 194, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [193, 195], description: 'Снег' },
  { number: 195, type: 'npc', icon: '❄️', color: '#ecf0f1', region: 'snow', connections: [194, 196], description: 'NPC: снежинка' },
  { number: 196, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [195, 197], description: 'Снег' },
  { number: 197, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [196, 198], description: 'Событие: ледяной шторм' },
  { number: 198, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [197, 199], description: 'Снег' },
  { number: 199, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [198, 200], description: 'Босс: ледяной дракон' },
  { number: 200, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [199, 201], description: 'Пустыня' },
  { number: 201, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [200, 202], description: 'Событие: найди воду' },
  { number: 202, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [201, 203], description: 'Сундук с водой' },
  { number: 203, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [202, 204], description: 'Пустыня' },
  { number: 204, type: 'npc', icon: '🌵', color: '#e67e22', region: 'desert', connections: [203, 205], description: 'NPC: кактус' },
  { number: 205, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [204, 206], description: 'Пустыня' },
  { number: 206, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [205, 207], description: 'Событие: кактус' },
  { number: 207, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [206, 208], description: 'Пустыня' },
  { number: 208, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [207, 209], description: 'Босс: кактус-гигант' },
  { number: 209, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [208, 210], description: 'Лес' },
  { number: 210, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [209, 211], description: 'Событие: найди ягоды' },
  { number: 211, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [210, 212], description: 'Сундук с ягодами' },
  { number: 212, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [211, 213], description: 'Лес' },
  { number: 213, type: 'npc', icon: '🐿️', color: '#2ecc71', region: 'forest', connections: [212, 214], description: 'NPC: белка' },
  { number: 214, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [213, 215], description: 'Лес' },
  { number: 215, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [214, 216], description: 'Событие: гриб' },
  { number: 216, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [215, 217], description: 'Лес' },
  { number: 217, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [216, 218], description: 'Босс: грибной монстр' },
  { number: 218, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [217, 219], description: 'Вода' },
  { number: 219, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [218, 220], description: 'Событие: найди водоросли' },
  { number: 220, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [219, 221], description: 'Сундук с водорослями' },
  { number: 221, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [220, 222], description: 'Вода' },
  { number: 222, type: 'npc', icon: '🦀', color: '#3498db', region: 'water', connections: [221, 223], description: 'NPC: краб' },
  { number: 223, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [222, 224], description: 'Вода' },
  { number: 224, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [223, 225], description: 'Событие: медуза' },
  { number: 225, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [224, 226], description: 'Вода' },
  { number: 226, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [225, 227], description: 'Босс: медузный монстр' },
  { number: 227, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [226, 228], description: 'Горы' },
  { number: 228, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [227, 229], description: 'Событие: найди кристалл' },
  { number: 229, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [228, 230], description: 'Сундук с кристаллом' },
  { number: 230, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [229, 231], description: 'Горы' },
  { number: 231, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [230, 232], description: 'NPC: кристалл' },
  { number: 232, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [231, 233], description: 'Горы' },
  { number: 233, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [232, 234], description: 'Событие: оползень' },
  { number: 234, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [233, 235], description: 'Горы' },
  { number: 235, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [234, 236], description: 'Босс: кристаллический дракон' },
  { number: 236, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [235, 237], description: 'Снег' },
  { number: 237, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [236, 238], description: 'Событие: найди снеговика' },
  { number: 238, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [237, 239], description: 'Сундук с снеговиком' },
  { number: 239, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [238, 240], description: 'Снег' },
  { number: 240, type: 'npc', icon: '☃️', color: '#ecf0f1', region: 'snow', connections: [239, 241], description: 'NPC: снеговик' },
  { number: 241, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [240, 242], description: 'Снег' },
  { number: 242, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [241, 243], description: 'Событие: снежок' },
  { number: 243, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [242, 244], description: 'Снег' },
  { number: 244, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [243, 245], description: 'Босс: снежный монстр' },
  { number: 245, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [244, 246], description: 'Лава' },
  { number: 246, type: 'event', icon: '✅', color: '#e74c3c', region: 'lava', connections: [245, 247], description: 'Событие: найди кристалл огня' },
  { number: 247, type: 'chest', icon: '💰', color: '#e74c3c', region: 'lava', connections: [246, 248], description: 'Сундук с кристаллом огня' },
  { number: 248, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [247, 249], description: 'Лава' },
  { number: 249, type: 'npc', icon: '🌋', color: '#e74c3c', region: 'lava', connections: [248, 250], description: 'NPC: вулкан' },
  { number: 250, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [249, 251], description: 'Лава' },
  { number: 251, type: 'event', icon: '❌', color: '#e74c3c', region: 'lava', connections: [250, 252], description: 'Событие: лавовый поток' },
  { number: 252, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [251, 253], description: 'Лава' },
  { number: 253, type: 'boss', icon: '🎯', color: '#e74c3c', region: 'lava', connections: [252, 254], description: 'Босс: огненный дракон' },
  { number: 254, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [253, 255], description: 'Пустыня' },
  { number: 255, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [254, 256], description: 'Событие: найди золото' },
  { number: 256, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [255, 257], description: 'Сундук с золотом' },
  { number: 257, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [256, 258], description: 'Пустыня' },
  { number: 258, type: 'npc', icon: '🐫', color: '#e67e22', region: 'desert', connections: [257, 259], description: 'NPC: верблюд' },
  { number: 259, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [258, 260], description: 'Пустыня' },
  { number: 260, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [259, 261], description: 'Событие: смерч' },
  { number: 261, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [260, 262], description: 'Пустыня' },
  { number: 262, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [261, 263], description: 'Босс: пустынный шейх' },
  { number: 263, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [262, 264], description: 'Лес' },
  { number: 264, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [263, 265], description: 'Событие: найди мёд' },
  { number: 265, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [264, 266], description: 'Сундук с мёдом' },
  { number: 266, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [265, 267], description: 'Лес' },
  { number: 267, type: 'npc', icon: '🐝', color: '#2ecc71', region: 'forest', connections: [266, 268], description: 'NPC: пчёлы' },
  { number: 268, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [267, 269], description: 'Лес' },
  { number: 269, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [268, 270], description: 'Событие: улей' },
  { number: 270, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [269, 271], description: 'Лес' },
  { number: 271, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [270, 272], description: 'Босс: королева пчёл' },
  { number: 272, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [271, 273], description: 'Вода' },
  { number: 273, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [272, 274], description: 'Событие: найди жемчужину' },
  { number: 274, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [273, 275], description: 'Сундук с жемчужиной' },
  { number: 275, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [274, 276], description: 'Вода' },
  { number: 276, type: 'npc', icon: '🐋', color: '#3498db', region: 'water', connections: [275, 277], description: 'NPC: кит' },
  { number: 277, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [276, 278], description: 'Вода' },
  { number: 278, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [277, 279], description: 'Событие: цунами' },
  { number: 279, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [278, 280], description: 'Вода' },
  { number: 280, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [279, 281], description: 'Босс: морской титан' },
  { number: 281, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [280, 282], description: 'Горы' },
  { number: 282, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [281, 283], description: 'Событие: найди алмаз' },
  { number: 283, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [282, 284], description: 'Сундук с алмазом' },
  { number: 284, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [283, 285], description: 'Горы' },
  { number: 285, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [284, 286], description: 'NPC: кристалл' },
  { number: 286, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [285, 287], description: 'Горы' },
  { number: 287, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [286, 288], description: 'Событие: оползень' },
  { number: 288, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [287, 289], description: 'Горы' },
  { number: 289, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [288, 290], description: 'Босс: алмазный гигант' },
  { number: 290, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [289, 291], description: 'Снег' },
  { number: 291, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [290, 292], description: 'Событие: найди снежинку' },
  { number: 292, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [291, 293], description: 'Сундук со снежинкой' },
  { number: 293, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [292, 294], description: 'Снег' },
  { number: 294, type: 'npc', icon: '❄️', color: '#ecf0f1', region: 'snow', connections: [293, 295], description: 'NPC: снежинка' },
  { number: 295, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [294, 296], description: 'Снег' },
  { number: 296, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [295, 297], description: 'Событие: ледяной шторм' },
  { number: 297, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [296, 298], description: 'Снег' },
  { number: 298, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [297, 299], description: 'Босс: ледяной дракон' },
  { number: 299, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [298, 300], description: 'Пустыня' },
  { number: 300, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [299, 301], description: 'Босс: король пустыни' },
  { number: 301, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [300, 302], description: 'Лес' },
  { number: 302, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [301, 303], description: 'Событие: найди яйцо' },
  { number: 303, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [302, 304], description: 'Сундук с яйцом' },
  { number: 304, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [303, 305], description: 'Лес' },
  { number: 305, type: 'npc', icon: '🦅', color: '#2ecc71', region: 'forest', connections: [304, 306], description: 'NPC: орёл' },
  { number: 306, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [305, 307], description: 'Лес' },
  { number: 307, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [306, 308], description: 'Событие: падение дерева' },
  { number: 308, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [307, 309], description: 'Лес' },
  { number: 309, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [308, 310], description: 'Босс: дракон-дятел' },
  { number: 310, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [309, 311], description: 'Вода' },
  { number: 311, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [310, 312], description: 'Событие: подводное плавание' },
  { number: 312, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [311, 313], description: 'Сундук с жемчужиной' },
  { number: 313, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [312, 314], description: 'Вода' },
  { number: 314, type: 'npc', icon: '🐬', color: '#3498db', region: 'water', connections: [313, 315], description: 'NPC: дельфин' },
  { number: 315, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [314, 316], description: 'Вода' },
  { number: 316, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [315, 317], description: 'Событие: акула' },
  { number: 317, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [316, 318], description: 'Вода' },
  { number: 318, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [317, 319], description: 'Босс: акулья стая' },
  { number: 319, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [318, 320], description: 'Горы' },
  { number: 320, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [319, 321], description: 'Событие: найди руду' },
  { number: 321, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [320, 322], description: 'Сундук с рудой' },
  { number: 322, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [321, 323], description: 'Горы' },
  { number: 323, type: 'npc', icon: '⛏️', color: '#9b59b6', region: 'mountains', connections: [322, 324], description: 'NPC: шахтёр' },
  { number: 324, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [323, 325], description: 'Горы' },
  { number: 325, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [324, 326], description: 'Событие: обвал' },
  { number: 326, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [325, 327], description: 'Горы' },
  { number: 327, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [326, 328], description: 'Босс: горный дракон' },
  { number: 328, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [327, 329], description: 'Снег' },
  { number: 329, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [328, 330], description: 'Событие: найди лед' },
  { number: 330, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [329, 331], description: 'Сундук с льдом' },
  { number: 331, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [330, 332], description: 'Снег' },
  { number: 332, type: 'npc', icon: '☃️', color: '#ecf0f1', region: 'snow', connections: [331, 333], description: 'NPC: снеговик' },
  { number: 333, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [332, 334], description: 'Снег' },
  { number: 334, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [333, 335], description: 'Событие: снежок' },
  { number: 335, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [334, 336], description: 'Снег' },
  { number: 336, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [335, 337], description: 'Босс: снежный монстр' },
  { number: 337, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [336, 338], description: 'Лава' },
  { number: 338, type: 'event', icon: '✅', color: '#e74c3c', region: 'lava', connections: [337, 339], description: 'Событие: найди кристалл огня' },
  { number: 339, type: 'chest', icon: '💰', color: '#e74c3c', region: 'lava', connections: [338, 340], description: 'Сундук с кристаллом' },
  { number: 340, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [339, 341], description: 'Лава' },
  { number: 341, type: 'npc', icon: '🌋', color: '#e74c3c', region: 'lava', connections: [340, 342], description: 'NPC: вулкан' },
  { number: 342, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [341, 343], description: 'Лава' },
  { number: 343, type: 'event', icon: '❌', color: '#e74c3c', region: 'lava', connections: [342, 344], description: 'Событие: лавовый поток' },
  { number: 344, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [343, 345], description: 'Лава' },
  { number: 345, type: 'boss', icon: '🎯', color: '#e74c3c', region: 'lava', connections: [344, 346], description: 'Босс: огненный дракон' },
  { number: 346, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [345, 347], description: 'Пустыня' },
  { number: 347, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [346, 348], description: 'Событие: найди золото' },
  { number: 348, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [347, 349], description: 'Сундук с золотом' },
  { number: 349, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [348, 350], description: 'Пустыня' },
  { number: 350, type: 'npc', icon: '🐫', color: '#e67e22', region: 'desert', connections: [349, 351], description: 'NPC: двугорбый верблюд' },
  { number: 351, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [350, 352], description: 'Пустыня' },
  { number: 352, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [351, 353], description: 'Событие: смерч' },
  { number: 353, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [352, 354], description: 'Пустыня' },
  { number: 354, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [353, 355], description: 'Босс: пустынный шейх' },
  { number: 355, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [354, 356], description: 'Лес' },
  { number: 356, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [355, 357], description: 'Событие: найди мёд' },
  { number: 357, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [356, 358], description: 'Сундук с мёдом' },
  { number: 358, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [357, 359], description: 'Лес' },
  { number: 359, type: 'npc', icon: '🐝', color: '#2ecc71', region: 'forest', connections: [358, 360], description: 'NPC: пчёлы' },
  { number: 360, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [359, 361], description: 'Лес' },
  { number: 361, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [360, 362], description: 'Событие: улей' },
  { number: 362, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [361, 363], description: 'Лес' },
  { number: 363, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [362, 364], description: 'Босс: королева пчёл' },
  { number: 364, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [363, 365], description: 'Вода' },
  { number: 365, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [364, 366], description: 'Событие: найди жемчужину' },
  { number: 366, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [365, 367], description: 'Сундук с жемчужиной' },
  { number: 367, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [366, 368], description: 'Вода' },
  { number: 368, type: 'npc', icon: '🐋', color: '#3498db', region: 'water', connections: [367, 369], description: 'NPC: кит' },
  { number: 369, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [368, 370], description: 'Вода' },
  { number: 370, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [369, 371], description: 'Событие: цунами' },
  { number: 371, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [370, 372], description: 'Вода' },
  { number: 372, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [371, 373], description: 'Босс: морской титан' },
  { number: 373, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [372, 374], description: 'Горы' },
  { number: 374, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [373, 375], description: 'Событие: найди алмаз' },
  { number: 375, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [374, 376], description: 'Сундук с алмазом' },
  { number: 376, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [375, 377], description: 'Горы' },
  { number: 377, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [376, 378], description: 'NPC: кристалл' },
  { number: 378, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [377, 379], description: 'Горы' },
  { number: 379, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [378, 380], description: 'Событие: оползень' },
  { number: 380, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [379, 381], description: 'Горы' },
  { number: 381, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [380, 382], description: 'Босс: алмазный гигант' },
  { number: 382, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [381, 383], description: 'Снег' },
  { number: 383, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [382, 384], description: 'Событие: найди снежинку' },
  { number: 384, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [383, 385], description: 'Сундук со снежинкой' },
  { number: 385, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [384, 386], description: 'Снег' },
  { number: 386, type: 'npc', icon: '❄️', color: '#ecf0f1', region: 'snow', connections: [385, 387], description: 'NPC: снежинка' },
  { number: 387, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [386, 388], description: 'Снег' },
  { number: 388, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [387, 389], description: 'Событие: ледяной шторм' },
  { number: 389, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [388, 390], description: 'Снег' },
  { number: 390, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [389, 391], description: 'Босс: ледяной дракон' },
  { number: 391, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [390, 392], description: 'Пустыня' },
  { number: 392, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [391, 393], description: 'Событие: найди воду' },
  { number: 393, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [392, 394], description: 'Сундук с водой' },
  { number: 394, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [393, 395], description: 'Пустыня' },
  { number: 395, type: 'npc', icon: '🌵', color: '#e67e22', region: 'desert', connections: [394, 396], description: 'NPC: кактус' },
  { number: 396, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [395, 397], description: 'Пустыня' },
  { number: 397, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [396, 398], description: 'Событие: кактус' },
  { number: 398, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [397, 399], description: 'Пустыня' },
  { number: 399, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [398, 400], description: 'Босс: кактус-гигант' },
  { number: 400, type: 'end', icon: '🏁', color: '#95a5a6', region: 'end', connections: [399], description: 'Финальная точка' },
  { number: 401, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [400, 402], description: 'Снег' },
  { number: 402, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [401, 403], description: 'Событие: найди снеговика' },
  { number: 403, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [402, 404], description: 'Сундук с снеговиком' },
  { number: 404, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [403, 405], description: 'Снег' },
  { number: 405, type: 'npc', icon: '☃️', color: '#ecf0f1', region: 'snow', connections: [404, 406], description: 'NPC: снеговик' },
  { number: 406, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [405, 407], description: 'Снег' },
  { number: 407, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [406, 408], description: 'Событие: снежок' },
  { number: 408, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [407, 409], description: 'Снег' },
  { number: 409, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [408, 410], description: 'Босс: снежный монстр' },
  { number: 410, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [409, 411], description: 'Лава' },
  { number: 411, type: 'event', icon: '✅', color: '#e74c3c', region: 'lava', connections: [410, 412], description: 'Событие: найди кристалл огня' },
  { number: 412, type: 'chest', icon: '💰', color: '#e74c3c', region: 'lava', connections: [411, 413], description: 'Сундук с кристаллом огня' },
  { number: 413, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [412, 414], description: 'Лава' },
  { number: 414, type: 'npc', icon: '🌋', color: '#e74c3c', region: 'lava', connections: [413, 415], description: 'NPC: вулкан' },
  { number: 415, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [414, 416], description: 'Лава' },
  { number: 416, type: 'event', icon: '❌', color: '#e74c3c', region: 'lava', connections: [415, 417], description: 'Событие: лавовый поток' },
  { number: 417, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [416, 418], description: 'Лава' },
  { number: 418, type: 'boss', icon: '🎯', color: '#e74c3c', region: 'lava', connections: [417, 419], description: 'Босс: огненный дракон' },
  { number: 419, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [418, 420], description: 'Пустыня' },
  { number: 420, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [419, 421], description: 'Событие: найди золото' },
  { number: 421, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [420, 422], description: 'Сундук с золотом' },
  { number: 422, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [421, 423], description: 'Пустыня' },
  { number: 423, type: 'npc', icon: '🐫', color: '#e67e22', region: 'desert', connections: [422, 424], description: 'NPC: верблюд' },
  { number: 424, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [423, 425], description: 'Пустыня' },
  { number: 425, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [424, 426], description: 'Событие: смерч' },
  { number: 426, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [425, 427], description: 'Пустыня' },
  { number: 427, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [426, 428], description: 'Босс: пустынный шейх' },
  { number: 428, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [427, 429], description: 'Лес' },
  { number: 429, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [428, 430], description: 'Событие: найди мёд' },
  { number: 430, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [429, 431], description: 'Сундук с мёдом' },
  { number: 431, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [430, 432], description: 'Лес' },
  { number: 432, type: 'npc', icon: '🐝', color: '#2ecc71', region: 'forest', connections: [431, 433], description: 'NPC: пчёлы' },
  { number: 433, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [432, 434], description: 'Лес' },
  { number: 434, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [433, 435], description: 'Событие: улей' },
  { number: 435, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [434, 436], description: 'Лес' },
  { number: 436, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [435, 437], description: 'Босс: королева пчёл' },
  { number: 437, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [436, 438], description: 'Вода' },
  { number: 438, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [437, 439], description: 'Событие: найди жемчужину' },
  { number: 439, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [438, 440], description: 'Сундук с жемчужиной' },
  { number: 440, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [439, 441], description: 'Вода' },
  { number: 441, type: 'npc', icon: '🐋', color: '#3498db', region: 'water', connections: [440, 442], description: 'NPC: кит' },
  { number: 442, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [441, 443], description: 'Вода' },
  { number: 443, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [442, 444], description: 'Событие: цунами' },
  { number: 444, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [443, 445], description: 'Вода' },
  { number: 445, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [444, 446], description: 'Босс: морской титан' },
  { number: 446, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [445, 447], description: 'Горы' },
  { number: 447, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [446, 448], description: 'Событие: найди алмаз' },
  { number: 448, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [447, 449], description: 'Сундук с алмазом' },
  { number: 449, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [448, 450], description: 'Горы' },
  { number: 450, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [449, 451], description: 'NPC: кристалл' },
  { number: 451, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [450, 452], description: 'Горы' },
  { number: 452, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [451, 453], description: 'Событие: оползень' },
  { number: 453, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [452, 454], description: 'Горы' },
  { number: 454, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [453, 455], description: 'Босс: алмазный гигант' },
  { number: 455, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [454, 456], description: 'Снег' },
  { number: 456, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [455, 457], description: 'Событие: найди снежинку' },
  { number: 457, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [456, 458], description: 'Сундук со снежинкой' },
  { number: 458, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [457, 459], description: 'Снег' },
  { number: 459, type: 'npc', icon: '❄️', color: '#ecf0f1', region: 'snow', connections: [458, 460], description: 'NPC: снежинка' },
  { number: 460, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [459, 461], description: 'Снег' },
  { number: 461, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [460, 462], description: 'Событие: ледяной шторм' },
  { number: 462, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [461, 463], description: 'Снег' },
  { number: 463, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [462, 464], description: 'Босс: ледяной дракон' },
  { number: 464, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [463, 465], description: 'Пустыня' },
  { number: 465, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [464, 466], description: 'Событие: найди воду' },
  { number: 466, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [465, 467], description: 'Сундук с водой' },
  { number: 467, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [466, 468], description: 'Пустыня' },
  { number: 468, type: 'npc', icon: '🌵', color: '#e67e22', region: 'desert', connections: [467, 469], description: 'NPC: кактус' },
  { number: 469, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [468, 470], description: 'Пустыня' },
  { number: 470, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [469, 471], description: 'Событие: кактус' },
  { number: 471, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [470, 472], description: 'Пустыня' },
  { number: 472, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [471, 473], description: 'Босс: кактус-гигант' },
  { number: 473, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [472, 474], description: 'Лес' },
  { number: 474, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [473, 475], description: 'Событие: найди ягоды' },
  { number: 475, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [474, 476], description: 'Сундук с ягодами' },
  { number: 476, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [475, 477], description: 'Лес' },
  { number: 477, type: 'npc', icon: '🐿️', color: '#2ecc71', region: 'forest', connections: [476, 478], description: 'NPC: белка' },
  { number: 478, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [477, 479], description: 'Лес' },
  { number: 479, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [478, 480], description: 'Событие: гриб' },
  { number: 480, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [479, 481], description: 'Лес' },
  { number: 481, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [480, 482], description: 'Босс: грибной монстр' },
  { number: 482, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [481, 483], description: 'Вода' },
  { number: 483, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [482, 484], description: 'Событие: найди водоросли' },
  { number: 484, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [483, 485], description: 'Сундук с водорослями' },
  { number: 485, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [484, 486], description: 'Вода' },
  { number: 486, type: 'npc', icon: '🦀', color: '#3498db', region: 'water', connections: [485, 487], description: 'NPC: краб' },
  { number: 487, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [486, 488], description: 'Вода' },
  { number: 488, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [487, 489], description: 'Событие: медуза' },
  { number: 489, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [488, 490], description: 'Вода' },
  { number: 490, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [489, 491], description: 'Босс: медузный монстр' },
  { number: 491, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [490, 492], description: 'Горы' },
  { number: 492, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [491, 493], description: 'Событие: найди кристалл' },
  { number: 493, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [492, 494], description: 'Сундук с кристаллом' },
  { number: 494, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [493, 495], description: 'Горы' },
  { number: 495, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [494, 496], description: 'NPC: кристалл' },
  { number: 496, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [495, 497], description: 'Горы' },
  { number: 497, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [496, 498], description: 'Событие: оползень' },
  { number: 498, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [497, 499], description: 'Горы' },
  { number: 499, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [498, 500], description: 'Босс: кристаллический дракон' },
  { number: 500, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [499, 501], description: 'Снег' },
  { number: 501, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [500, 502], description: 'Событие: найди снежинку' },
  { number: 502, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [501, 503], description: 'Сундук со снежинкой' },
  { number: 503, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [502, 504], description: 'Снег' },
  { number: 504, type: 'npc', icon: '❄️', color: '#ecf0f1', region: 'snow', connections: [503, 505], description: 'NPC: снежинка' },
  { number: 505, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [504, 506], description: 'Снег' },
  { number: 506, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [505, 507], description: 'Событие: ледяной шторм' },
  { number: 507, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [506, 508], description: 'Снег' },
  { number: 508, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [507, 509], description: 'Босс: ледяной дракон' },
  { number: 509, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [508, 510], description: 'Лава' },
  { number: 510, type: 'event', icon: '✅', color: '#e74c3c', region: 'lava', connections: [509, 511], description: 'Событие: найди кристалл огня' },
  { number: 511, type: 'chest', icon: '💰', color: '#e74c3c', region: 'lava', connections: [510, 512], description: 'Сундук с кристаллом огня' },
  { number: 512, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [511, 513], description: 'Лава' },
  { number: 513, type: 'npc', icon: '🌋', color: '#e74c3c', region: 'lava', connections: [512, 514], description: 'NPC: вулкан' },
  { number: 514, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [513, 515], description: 'Лава' },
  { number: 515, type: 'event', icon: '❌', color: '#e74c3c', region: 'lava', connections: [514, 516], description: 'Событие: лавовый поток' },
  { number: 516, type: 'normal', icon: '', color: '#e74c3c', region: 'lava', connections: [515, 517], description: 'Лава' },
  { number: 517, type: 'boss', icon: '🎯', color: '#e74c3c', region: 'lava', connections: [516, 518], description: 'Босс: огненный дракон' },
  { number: 518, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [517, 519], description: 'Пустыня' },
  { number: 519, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [518, 520], description: 'Событие: найди золото' },
  { number: 520, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [519, 521], description: 'Сундук с золотом' },
  { number: 521, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [520, 522], description: 'Пустыня' },
  { number: 522, type: 'npc', icon: '🐫', color: '#e67e22', region: 'desert', connections: [521, 523], description: 'NPC: верблюд' },
  { number: 523, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [522, 524], description: 'Пустыня' },
  { number: 524, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [523, 525], description: 'Событие: смерч' },
  { number: 525, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [524, 526], description: 'Пустыня' },
  { number: 526, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [525, 527], description: 'Босс: пустынный шейх' },
  { number: 527, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [526, 528], description: 'Лес' },
  { number: 528, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [527, 529], description: 'Событие: найди мёд' },
  { number: 529, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [528, 530], description: 'Сундук с мёдом' },
  { number: 530, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [529, 531], description: 'Лес' },
  { number: 531, type: 'npc', icon: '🐝', color: '#2ecc71', region: 'forest', connections: [530, 532], description: 'NPC: пчёлы' },
  { number: 532, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [531, 533], description: 'Лес' },
  { number: 533, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [532, 534], description: 'Событие: улей' },
  { number: 534, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [533, 535], description: 'Лес' },
  { number: 535, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [534, 536], description: 'Босс: королева пчёл' },
  { number: 536, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [535, 537], description: 'Вода' },
  { number: 537, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [536, 538], description: 'Событие: найди жемчужину' },
  { number: 538, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [537, 539], description: 'Сундук с жемчужиной' },
  { number: 539, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [538, 540], description: 'Вода' },
  { number: 540, type: 'npc', icon: '🐋', color: '#3498db', region: 'water', connections: [539, 541], description: 'NPC: кит' },
  { number: 541, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [540, 542], description: 'Вода' },
  { number: 542, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [541, 543], description: 'Событие: цунами' },
  { number: 543, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [542, 544], description: 'Вода' },
  { number: 544, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [543, 545], description: 'Босс: морской титан' },
  { number: 545, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [544, 546], description: 'Горы' },
  { number: 546, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [545, 547], description: 'Событие: найди алмаз' },
  { number: 547, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [546, 548], description: 'Сундук с алмазом' },
  { number: 548, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [547, 549], description: 'Горы' },
  { number: 549, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [548, 550], description: 'NPC: кристалл' },
  { number: 550, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [549, 551], description: 'Горы' },
  { number: 551, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [550, 552], description: 'Событие: оползень' },
  { number: 552, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [551, 553], description: 'Горы' },
  { number: 553, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [552, 554], description: 'Босс: алмазный гигант' },
  { number: 554, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [553, 555], description: 'Снег' },
  { number: 555, type: 'event', icon: '✅', color: '#ecf0f1', region: 'snow', connections: [554, 556], description: 'Событие: найди снежинку' },
  { number: 556, type: 'chest', icon: '💰', color: '#ecf0f1', region: 'snow', connections: [555, 557], description: 'Сундук со снежинкой' },
  { number: 557, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [556, 558], description: 'Снег' },
  { number: 558, type: 'npc', icon: '❄️', color: '#ecf0f1', region: 'snow', connections: [557, 559], description: 'NPC: снежинка' },
  { number: 559, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [558, 560], description: 'Снег' },
  { number: 560, type: 'event', icon: '❌', color: '#ecf0f1', region: 'snow', connections: [559, 561], description: 'Событие: ледяной шторм' },
  { number: 561, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [560, 562], description: 'Снег' },
  { number: 562, type: 'boss', icon: '🎯', color: '#ecf0f1', region: 'snow', connections: [561, 563], description: 'Босс: ледяной дракон' },
  { number: 563, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [562, 564], description: 'Пустыня' },
  { number: 564, type: 'event', icon: '✅', color: '#e67e22', region: 'desert', connections: [563, 565], description: 'Событие: найди воду' },
  { number: 565, type: 'chest', icon: '💰', color: '#e67e22', region: 'desert', connections: [564, 566], description: 'Сундук с водой' },
  { number: 566, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [565, 567], description: 'Пустыня' },
  { number: 567, type: 'npc', icon: '🌵', color: '#e67e22', region: 'desert', connections: [566, 568], description: 'NPC: кактус' },
  { number: 568, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [567, 569], description: 'Пустыня' },
  { number: 569, type: 'event', icon: '❌', color: '#e67e22', region: 'desert', connections: [568, 570], description: 'Событие: кактус' },
  { number: 570, type: 'normal', icon: '', color: '#e67e22', region: 'desert', connections: [569, 571], description: 'Пустыня' },
  { number: 571, type: 'boss', icon: '🎯', color: '#e67e22', region: 'desert', connections: [570, 572], description: 'Босс: кактус-гигант' },
  { number: 572, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [571, 573], description: 'Лес' },
  { number: 573, type: 'event', icon: '✅', color: '#2ecc71', region: 'forest', connections: [572, 574], description: 'Событие: найди ягоды' },
  { number: 574, type: 'chest', icon: '💰', color: '#2ecc71', region: 'forest', connections: [573, 575], description: 'Сундук с ягодами' },
  { number: 575, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [574, 576], description: 'Лес' },
  { number: 576, type: 'npc', icon: '🐿️', color: '#2ecc71', region: 'forest', connections: [575, 577], description: 'NPC: белка' },
  { number: 577, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [576, 578], description: 'Лес' },
  { number: 578, type: 'event', icon: '❌', color: '#2ecc71', region: 'forest', connections: [577, 579], description: 'Событие: гриб' },
  { number: 579, type: 'normal', icon: '', color: '#2ecc71', region: 'forest', connections: [578, 580], description: 'Лес' },
  { number: 580, type: 'boss', icon: '🎯', color: '#2ecc71', region: 'forest', connections: [579, 581], description: 'Босс: грибной монстр' },
  { number: 581, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [580, 582], description: 'Вода' },
  { number: 582, type: 'event', icon: '✅', color: '#3498db', region: 'water', connections: [581, 583], description: 'Событие: найди водоросли' },
  { number: 583, type: 'chest', icon: '💰', color: '#3498db', region: 'water', connections: [582, 584], description: 'Сундук с водорослями' },
  { number: 584, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [583, 585], description: 'Вода' },
  { number: 585, type: 'npc', icon: '🦀', color: '#3498db', region: 'water', connections: [584, 586], description: 'NPC: краб' },
  { number: 586, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [585, 587], description: 'Вода' },
  { number: 587, type: 'event', icon: '❌', color: '#3498db', region: 'water', connections: [586, 588], description: 'Событие: медуза' },
  { number: 588, type: 'normal', icon: '', color: '#3498db', region: 'water', connections: [587, 589], description: 'Вода' },
  { number: 589, type: 'boss', icon: '🎯', color: '#3498db', region: 'water', connections: [588, 590], description: 'Босс: медузный монстр' },
  { number: 590, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [589, 591], description: 'Горы' },
  { number: 591, type: 'event', icon: '✅', color: '#9b59b6', region: 'mountains', connections: [590, 592], description: 'Событие: найди кристалл' },
  { number: 592, type: 'chest', icon: '💰', color: '#9b59b6', region: 'mountains', connections: [591, 593], description: 'Сундук с кристаллом' },
  { number: 593, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [592, 594], description: 'Горы' },
  { number: 594, type: 'npc', icon: '💎', color: '#9b59b6', region: 'mountains', connections: [593, 595], description: 'NPC: кристалл' },
  { number: 595, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [594, 596], description: 'Горы' },
  { number: 596, type: 'event', icon: '❌', color: '#9b59b6', region: 'mountains', connections: [595, 597], description: 'Событие: оползень' },
  { number: 597, type: 'normal', icon: '', color: '#9b59b6', region: 'mountains', connections: [596, 598], description: 'Горы' },
  { number: 598, type: 'boss', icon: '🎯', color: '#9b59b6', region: 'mountains', connections: [597, 599], description: 'Босс: кристаллический дракон' },
  { number: 599, type: 'normal', icon: '', color: '#ecf0f1', region: 'snow', connections: [598, 600], description: 'Снег' },
  { number: 600, type: 'end', icon: '🏁', color: '#95a5a6', region: 'end', connections: [599], description: 'Финальная точка' }
];